import type { QuoteRecord, SlangMapping } from "@/lib/types";
import { BLESSING_QUOTES, BLESSING_SLANG_MAPPINGS } from "./blessing-corpus";
import { CLASSIC_QUOTES, CLASSIC_SLANG_MAPPINGS } from "./classic-corpus";

export const QUOTES: QuoteRecord[] = [
  ...CLASSIC_QUOTES,
  ...BLESSING_QUOTES,
  { id: "li-bai-xuanzhou-emo", quote: "抽刀断水水更流，举杯消愁愁更愁。", title: "宣州谢朓楼饯别校书叔云", author: "李白", dynasty: "唐", source: "全唐诗", context: "弃我去者，昨日之日不可留；乱我心者，今日之日多烦忧。", translation: "想借酒消愁，反而愁绪更深。", themes: ["忧愁", "失意", "烦闷"], modernMeanings: ["我 emo 了", "破防了", "心态崩了"], emotion: "sad", scene: ["情绪", "夜晚", "低落"], weight: 98 },
  { id: "li-bai-xinglunan-stable", quote: "长风破浪会有时，直挂云帆济沧海。", title: "行路难·其一", author: "李白", dynasty: "唐", source: "全唐诗", context: "行路难，行路难，多歧路，今安在？", translation: "相信终有一天能冲破阻碍，实现理想。", themes: ["希望", "信心", "成功", "逆境"], modernMeanings: ["这事包的", "稳了", "未来可期", "一定能成"], emotion: "positive", scene: ["考试", "创业", "鼓励"], weight: 100 },
  { id: "tao-yuanming-yinju-tangping", quote: "采菊东篱下，悠然见南山。", title: "饮酒·其五", author: "陶渊明", dynasty: "东晋", source: "陶渊明集", context: "结庐在人境，而无车马喧。", translation: "远离喧嚣，在平淡生活里获得松弛和自在。", themes: ["松弛", "归隐", "自由", "不争"], modernMeanings: ["躺平", "不想卷", "想退休", "佛系"], emotion: "calm", scene: ["工作", "生活", "田园"], weight: 96 },
  { id: "du-fu-li-bai-awesome", quote: "笔落惊风雨，诗成泣鬼神。", title: "寄李十二白二十韵", author: "杜甫", dynasty: "唐", source: "全唐诗", context: "昔年有狂客，号尔谪仙人。", translation: "形容才华极其惊人，作品震撼人心。", themes: ["赞美", "才华", "震撼"], modernMeanings: ["太牛了", "666", "封神", "绝绝子"], emotion: "admire", scene: ["夸人", "作品", "能力"], weight: 95 },
  { id: "li-bai-jiangjinjiu-happy", quote: "人生得意须尽欢，莫使金樽空对月。", title: "将进酒", author: "李白", dynasty: "唐", source: "全唐诗", context: "君不见黄河之水天上来，奔流到海不复回。", translation: "人生得意之时就要尽情欢快，不要辜负当下。", themes: ["快乐", "得意", "畅快"], modernMeanings: ["太爽了", "舒服了", "开心到飞起"], emotion: "happy", scene: ["庆祝", "聚会", "开心"], weight: 94 },
  { id: "shijing-tianbao-birthday", quote: "如月之恒，如日之升，如南山之寿，不骞不崩。如松柏之茂，无不尔或承。", title: "天保", author: "佚名", dynasty: "先秦", source: "诗经", context: "天保定尔，亦孔之固。俾尔单厚，何福不除？如月之恒，如日之升，如南山之寿，不骞不崩。如松柏之茂，无不尔或承。", translation: "这是《诗经》里经典的贺生祝福语，常用于祝寿庆生，意思是愿人像日月恒久、南山长寿、松柏长青。", themes: ["祝福", "生日", "喜庆", "长寿"], modernMeanings: ["生日快乐", "祝你生日快乐", "生辰快乐", "生日祝福", "祝寿"], emotion: "happy", scene: ["生日", "庆生", "祝福"], weight: 126 },
  { id: "wangwei-miss-home", quote: "独在异乡为异客，每逢佳节倍思亲。", title: "九月九日忆山东兄弟", author: "王维", dynasty: "唐", source: "全唐诗", context: "遥知兄弟登高处，遍插茱萸少一人。", translation: "独自在外地，逢年过节尤其想念亲人。", themes: ["思乡", "漂泊", "亲情"], modernMeanings: ["想家了", "异乡人", "一个人在外"], emotion: "homesick", scene: ["节日", "离家", "漂泊"], weight: 93 },
  { id: "yueyanglou-letgo", quote: "不以物喜，不以己悲。", title: "岳阳楼记", author: "范仲淹", dynasty: "北宋", source: "范文正公集", context: "予尝求古仁人之心，或异二者之为。", translation: "不因外物好坏和个人得失而大喜大悲。", themes: ["释怀", "豁达", "通透"], modernMeanings: ["看开了", "放下了", "不纠结"], emotion: "relieved", scene: ["情绪", "得失", "人生"], weight: 91 },
  { id: "su-shi-dingfengbo-letgo", quote: "回首向来萧瑟处，归去，也无风雨也无晴。", title: "定风波·莫听穿林打叶声", author: "苏轼", dynasty: "北宋", source: "东坡乐府", context: "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。", translation: "经历风雨后回头看，一切都可以放下。", themes: ["释怀", "豁达", "通透"], modernMeanings: ["算了", "释怀了", "不内耗了"], emotion: "relieved", scene: ["人生", "挫折", "雨天"], weight: 94 },
  { id: "xunzi-work-hard", quote: "不积跬步，无以至千里；不积小流，无以成江海。", title: "劝学", author: "荀子", dynasty: "战国", source: "荀子", context: "故不积跬步，无以至千里；不积小流，无以成江海。", translation: "再远的目标，也要靠一点点积累完成。", themes: ["努力", "坚持", "成长"], modernMeanings: ["坚持自律", "慢慢变强", "上岸"], emotion: "driven", scene: ["学习", "考试", "成长"], weight: 95 },
  { id: "zhengxie-work-hard", quote: "千磨万击还坚劲，任尔东西南北风。", title: "竹石", author: "郑燮", dynasty: "清", source: "板桥集", context: "咬定青山不放松，立根原在破岩中。", translation: "经历很多打击，仍然坚韧不屈。", themes: ["坚持", "逆境", "韧性"], modernMeanings: ["别放弃", "扛住", "逆袭"], emotion: "driven", scene: ["困难", "创业", "备考"], weight: 92 },
  { id: "wangbo-friend", quote: "海内存知己，天涯若比邻。", title: "送杜少府之任蜀州", author: "王勃", dynasty: "唐", source: "全唐诗", context: "与君离别意，同是宦游人。", translation: "只要彼此是知己，相隔再远也像近邻。", themes: ["友情", "知己", "陪伴"], modernMeanings: ["同频朋友", "你懂我", "好兄弟"], emotion: "warm", scene: ["朋友", "离别", "陪伴"], weight: 91 },
  { id: "shijing-love", quote: "青青子衿，悠悠我心。", title: "子衿", author: "佚名", dynasty: "先秦", source: "诗经", context: "纵我不往，子宁不嗣音？", translation: "对所思之人念念不忘，心意绵长。", themes: ["相思", "爱情", "心动"], modernMeanings: ["心动了", "想见你", "念念不忘"], emotion: "love", scene: ["喜欢", "暗恋", "思念"], weight: 90 },
  { id: "mulan-speechless", quote: "雄兔脚扑朔，雌兔眼迷离；双兔傍地走，安能辨我是雄雌？", title: "木兰诗", author: "佚名", dynasty: "南北朝", source: "乐府诗集", context: "出门看火伴，火伴皆惊忙。", translation: "事情复杂到难以分辨，让人有些看不懂。", themes: ["无语", "荒诞", "复杂"], modernMeanings: ["离谱", "看不懂", "我真的会谢"], emotion: "speechless", scene: ["吐槽", "反转", "复杂"], weight: 84 },
  { id: "tao-yuanming-guiqulai", quote: "归去来兮，田园将芜胡不归？", title: "归去来兮辞", author: "陶渊明", dynasty: "东晋", source: "陶渊明集", context: "悟已往之不谏，知来者之可追。", translation: "厌倦奔忙后，想回到更自在的生活。", themes: ["归隐", "自由", "松弛"], modernMeanings: ["不想上班", "想回家", "想躺平"], emotion: "calm", scene: ["工作", "生活", "田园"], weight: 88 },
  { id: "shijing-shuoren-beauty", quote: "巧笑倩兮，美目盼兮。", title: "硕人", author: "佚名", dynasty: "先秦", source: "诗经", context: "手如柔荑，肤如凝脂，领如蝤蛴，齿如瓠犀。巧笑倩兮，美目盼兮。", translation: "形容笑容动人、眼神明亮，是夸人好看的经典表达。", themes: ["美貌", "赞美", "容貌"], modernMeanings: ["你真好看", "你好漂亮", "颜值高", "太美了"], emotion: "beauty", scene: ["夸人", "容貌", "心动"], weight: 110 },
  { id: "li-yannian-beauty", quote: "北方有佳人，绝世而独立。", title: "李延年歌", author: "李延年", dynasty: "汉", source: "汉书·外戚传", context: "北方有佳人，绝世而独立。一顾倾人城，再顾倾人国。", translation: "赞叹佳人姿容出众、气质独立，可对应“你真好看”。", themes: ["美貌", "赞美", "惊艳"], modernMeanings: ["你真好看", "太漂亮了", "美到惊艳", "颜值天花板"], emotion: "beauty", scene: ["夸人", "容貌", "惊艳"], weight: 109 },
  { id: "li-bai-qingpingdiao-beauty", quote: "云想衣裳花想容，春风拂槛露华浓。", title: "清平调·其一", author: "李白", dynasty: "唐", source: "全唐诗", context: "云想衣裳花想容，春风拂槛露华浓。", translation: "以云霞花容写人的美貌，适合表达“好看”“漂亮”“惊艳”。", themes: ["美貌", "赞美", "惊艳"], modernMeanings: ["你真好看", "你好美", "太惊艳了", "漂亮"], emotion: "beauty", scene: ["夸人", "容貌", "惊艳"], weight: 108 },
  { id: "bai-juyi-changhenge-beauty", quote: "回眸一笑百媚生，六宫粉黛无颜色。", title: "长恨歌", author: "白居易", dynasty: "唐", source: "全唐诗", context: "回眸一笑百媚生，六宫粉黛无颜色。", translation: "写回眸一笑便风姿万千，是夸人美得出众的经典句。", themes: ["美貌", "赞美", "惊艳"], modernMeanings: ["你真好看", "笑起来真好看", "太美了", "颜值高"], emotion: "beauty", scene: ["夸人", "容貌", "笑容"], weight: 107 }
];

export const SLANG_MAPPINGS: SlangMapping[] = [
  ...CLASSIC_SLANG_MAPPINGS,
  ...BLESSING_SLANG_MAPPINGS,
  { id: "emo", patterns: ["emo", "破防", "心态崩", "崩了", "难受", "低落", "丧"], keywords: ["忧愁", "失意", "烦忧", "愁", "伤心", "惆怅", "心碎", "孤独"], themes: ["忧愁", "失意", "孤独"], emotion: "sad", explanation: "表达低落、烦乱、情绪失控或心里难受。" },
  { id: "awesome", patterns: ["牛", "太强", "厉害", "666", "绝绝子", "封神", "天花板", "顶级"], keywords: ["惊", "绝", "壮", "奇", "豪", "才华", "惊艳", "卓绝"], themes: ["赞美", "才华", "震撼"], emotion: "admire", explanation: "表达强烈赞叹、佩服和“太厉害了”。" },
  { id: "beauty", patterns: ["好看", "真好看", "你好看", "你真好看", "漂亮", "真漂亮", "好美", "真美", "太美", "颜值", "美貌", "美女", "帅", "好帅"], keywords: ["美貌", "赞美", "容貌", "惊艳", "佳人", "美目", "花想容", "回眸", "百媚", "漂亮"], themes: ["美貌", "赞美", "惊艳"], emotion: "beauty", explanation: "表达对外貌、气质、笑容或颜值的赞美，比如“你好看”“太漂亮了”。" },
  { id: "stable", patterns: ["包的", "稳了", "拿下", "一定能成", "没问题", "放心", "未来可期"], keywords: ["会有时", "济沧海", "益坚", "成功", "志向", "信心", "希望"], themes: ["希望", "信心", "成功"], emotion: "positive", explanation: "表达有把握、有信心、相信事情最终会成功。" },
  { id: "tangping", patterns: ["躺平", "不想卷", "摆烂", "不想上班", "想退休", "松弛", "佛系"], keywords: ["悠然", "南山", "归去", "自在", "闲", "不争", "山水", "田园"], themes: ["松弛", "归隐", "自由"], emotion: "calm", explanation: "表达想远离内卷、回到轻松自在的状态。" },
  { id: "juan", patterns: ["内卷", "太卷", "卷不动", "压力大", "焦虑", "好累", "累了"], keywords: ["辛苦", "劳", "忧患", "难", "跬步", "坚持", "逆境", "不易"], themes: ["压力", "坚持", "逆境"], emotion: "stressed", explanation: "表达压力、疲惫、竞争和焦虑。" },
  { id: "speechless", patterns: ["我真的会谢", "无语", "离谱", "蚌埠住", "麻了", "裂开", "服了"], keywords: ["奈何", "无可奈何", "叹", "愁", "啼笑", "无言", "怅然"], themes: ["无奈", "心累", "荒诞"], emotion: "speechless", explanation: "表达无语、心累、被现实整不会了。" },
  { id: "miss-home", patterns: ["想家", "思乡", "异乡", "孤身一人", "漂泊", "离家"], keywords: ["故乡", "明月", "异乡", "归", "乡", "客", "思亲"], themes: ["思乡", "漂泊", "亲情"], emotion: "homesick", explanation: "表达离家在外、想念亲人和故乡。" },
  { id: "love", patterns: ["喜欢", "心动", "暗恋", "想见你", "恋爱脑", "crush", "念念不忘"], keywords: ["伊人", "相思", "青青子衿", "执手", "见", "情", "念"], themes: ["相思", "爱情", "心动"], emotion: "love", explanation: "表达喜欢、思念、心动或念念不忘。" },
  { id: "friend", patterns: ["好兄弟", "知己", "朋友", "你懂我", "同频", "陪伴"], keywords: ["知己", "天涯", "朋友", "同是", "相逢", "莫愁"], themes: ["友情", "知己", "陪伴"], emotion: "warm", explanation: "表达被理解、朋友陪伴和知己之情。" },
  { id: "work-hard", patterns: ["努力", "自律", "搞钱", "上岸", "冲", "逆袭", "不要放弃", "坚持"], keywords: ["跬步", "千里", "破浪", "益坚", "努力", "志", "百战", "穿金甲"], themes: ["努力", "坚持", "成长"], emotion: "driven", explanation: "表达努力向上、坚持、逆袭和长期主义。" },
  { id: "birthday", patterns: ["生日快乐", "祝你生日快乐", "生辰快乐", "过生日", "庆生", "祝寿"], keywords: ["祝福", "生辰", "寿", "南山", "松柏", "嘉庆", "长乐"], themes: ["祝福", "生日", "喜庆"], emotion: "happy", explanation: "表达生日祝福、庆生或祝寿，希望找到更贴切的古文贺词。" },
  { id: "happy", patterns: ["开心", "爽", "舒服了", "快乐", "太香了", "人生得意"], keywords: ["春风得意", "尽欢", "快意", "乐", "欢", "得意"], themes: ["快乐", "得意", "畅快"], emotion: "happy", explanation: "表达开心、畅快、人生得意的状态。" },
  { id: "let-go", patterns: ["释怀", "算了", "放下", "看开", "别想了", "不纠结"], keywords: ["不以物喜", "不以己悲", "归去", "无风雨", "也无晴", "看开"], themes: ["释怀", "豁达", "通透"], emotion: "relieved", explanation: "表达看开、放下和不再纠结。" }
];
